#!/usr/bin/env python3
"""Embed a binary file into a C++ source file.

Usage:
    embed_binary.py --input FILE --symbol NAME --output FILE [--type bytes|words]

Generates:
    #include <cstddef>
    extern const unsigned char NAME[];  (or extern const uint32_t NAME[];)
    const size_t NAME_SIZE = N;

'words' reinterprets the file as little-endian 32-bit words (for SPIR-V).
"""

import argparse


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--symbol", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--type", choices=["bytes", "words"], default="bytes")
    args = parser.parse_args()

    with open(args.input, "rb") as f:
        data = f.read()

    with open(args.output, "w", encoding="utf-8") as out:
        out.write("// Generated by tools/embed_binary.py — do not edit.\n")
        out.write("#include <cstddef>\n#include <cstdint>\n\n")
        if args.type == "words":
            out.write(f"extern const uint32_t {args.symbol}[] = {{\n")
            for i in range(0, len(data), 4):
                word = int.from_bytes(data[i:i + 4], "little")
                out.write(f"0x{word:08x}u, ")
                if (i // 4) % 8 == 7:
                    out.write("\n")
            word_count = (len(data) + 3) // 4
            out.write("\n};\n")
            out.write(f"extern const size_t {args.symbol}_SIZE = {word_count};\n")
        else:
            out.write(f"extern const unsigned char {args.symbol}[] = {{\n")
            for i, byte in enumerate(data):
                out.write(f"0x{byte:02x}, ")
                if i % 32 == 31:
                    out.write("\n")
            out.write("\n};\n")
            out.write(f"extern const size_t {args.symbol}_SIZE = {len(data)};\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
