// Font binaries embedded into the binary (generated by tools/embed_binary.py).
#pragma once

#include <cstddef>

extern const unsigned char FONT_REGULAR_TTF[];
extern const size_t FONT_REGULAR_TTF_SIZE;
extern const unsigned char FONT_BOLD_TTF[];
extern const size_t FONT_BOLD_TTF_SIZE;
